// <auto-generated />
namespace PavillionData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addchatcodetocontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addchatcodetocontext));
        
        string IMigrationMetadata.Id
        {
            get { return "202108211515201_add-chatcode-to-context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
